### ISSUE TITLE
Epic: Detail page

### ISSUE THREAD

**Issue by konrascher3** [konrascher3/nf-capstone#48]
- [x] Should show chart
- [x] Should show detail-header
- [x] Should show macro-data
- [x] Should show "About"-section
